### ISSUE TITLE
[question]: No way to add new Thinos in Moments view

### ISSUE THREAD

**Issue by lifehaschanged** [Quorafind/Obsidian-Thino#652]
### Bug Description | BUG 描述

Maybe I'm blind but I can't see a button or a working command to insert a new Thino when you are inside the moments view (sidebar). There is a working "show thino editor" command: It's showing up, but only with the text of a previous selected Thino inside. You can't open the "show thino editor" command without any text inside from moments view?

### Relevant Screenshot | 相关截图

![grafik](https://github.com/Quorafind/Obsidian-Thino/assets/81463128/cd0b8ac5-471a-4b40-ae07-4ae363054e28)

### Obsidian Version | Obsidian 版本

1.6.2

### Which editor are you using? (If applicable)

- [ ] New Editor (WYSIWYG) | 新编辑器
- [ ] Legacy Editor (Markdown) | 旧编辑器

### Checklist

- [X] I updated to the latest version of the plugin. 我更新到了插件的最新版本。

**Comment by juestchaos** [comment]
You can try clicking on the camera icon at the header position, or use the shortcut keys of thino.
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/c3172ee8-93ee-41ba-bc19-df60e0f85745)
![image](https://github.com/Quorafind/Obsidian-Thino/assets/241007/9a82c879-c446-483c-8429-e9b8eb441332)

**Comment by juestchaos** [comment]
I have not encountered this situation before. However, in order to protect user data and prevent crashes or loss of input when trying out other plugins, thino caches the previous data locally for users. Therefore, your situation may be caused by this. Generally, deleting the cache, recording new content, and saving it normally should resolve the issue.
